// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dojbtnunusuyunvmfwtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvamJ0bnVudXN1eXVudm1md3RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDc4OTcsImV4cCI6MjA3NDQ4Mzg5N30.XFQ_MJnHYM1ds7IyBCcPEbyOHN3aDmoxRrm2URPNOaU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});